// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
	"bytes"
)


/**
 * ------------------------------------------------------------------------
 * 🛰️ VOID PROTOCOL v2.1 | Tiny Innovation Group Ltd
 * -------------------------------------------------------------------------
 * Authority: Tiny Innovation Group Ltd
 * License:   Apache 2.0
 * Status:    Authenticated Clean Room Spec
 * File:      void_protocol.ksy
 * Desc:      A Kaitai Struct file(KSY) containing the dual-header aerospace protocol for orbital settlement.
 * -------------------------------------------------------------------------
 * 
 * VOID Protocol v2.1 (Layer 2 M2M Settlement)
 * 
 * ## Routing Architecture
 * This parser automatically distinguishes between two physical layer frame formats:
 * 1. Community Tier (SNLP): Optimized for LoRa/ISM bands (433/868/915 MHz). 
 *    Identified by the Sync Word `0x1D01A5A5`. Uses a 14-byte header.
 * 2. Enterprise Tier (CCSDS): Standard S-Band/X-Band format. 
 *    Uses a strict 6-byte CCSDS Space Packet Protocol header.
 * 
 * ## Public Data Mandate
 * As per the TinyGS operational requirement, all traffic routed via the SNLP (Community) 
 * path is treated as PUBLIC DOMAIN. The `enc_payload` field in Packet B is transmitted 
 * in plaintext when using SNLP to ensure compliance with amateur radio encryption bans.
 * @see <a href="https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/README.md">https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/docs/Acknowledgment-spec.md https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/docs/Protocol-spec-CCSDS.md https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/docs/Protocol-spec-SNLP.md https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/docs/Receipt-spec.md</a>
 */
type VoidProtocol struct {
	RoutingHeader kaitai.Struct
	Body kaitai.Struct
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent kaitai.Struct
	_f_globalApid bool
	globalApid int
	_f_globalPacketType bool
	globalPacketType int
	_f_isSnlp bool
	isSnlp bool
	_f_magicPeek bool
	magicPeek uint32
	_f_payloadLen bool
	payloadLen int
}
func NewVoidProtocol() *VoidProtocol {
	return &VoidProtocol{
	}
}

func (this VoidProtocol) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol) Read(io *kaitai.Stream, parent kaitai.Struct, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._root.IsSnlp()
	if err != nil {
		return err
	}
	switch (tmp1) {
	case false:
		tmp2 := NewVoidProtocol_HeaderCcsds()
		err = tmp2.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.RoutingHeader = tmp2
	case true:
		tmp3 := NewVoidProtocol_HeaderSnlp()
		err = tmp3.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.RoutingHeader = tmp3
	}
	tmp4, err := this.PayloadLen()
	if err != nil {
		return err
	}
	switch (tmp4) {
	case 106:
		tmp5 := NewVoidProtocol_PacketHBody()
		err = tmp5.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp5
	case 114:
		tmp6 := NewVoidProtocol_PacketAckBody()
		err = tmp6.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp6
	case 122:
		tmp7 := NewVoidProtocol_Dispatch122()
		err = tmp7.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp7
	case 170:
		tmp8 := NewVoidProtocol_PacketBBody()
		err = tmp8.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp8
	case 34:
		tmp9 := NewVoidProtocol_HeartbeatBody()
		err = tmp9.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp9
	case 62:
		tmp10 := NewVoidProtocol_PacketABody()
		err = tmp10.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp10
	case 98:
		tmp11 := NewVoidProtocol_PacketCBody()
		err = tmp11.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp11
	}
	return err
}
func (this *VoidProtocol) GlobalApid() (v int, err error) {
	if (this._f_globalApid) {
		return this.globalApid, nil
	}
	this._f_globalApid = true
	var tmp12 int;
	tmp13, err := this.IsSnlp()
	if err != nil {
		return 0, err
	}
	if (tmp13) {
		tmp14, err := this.RoutingHeader.(*VoidProtocol_HeaderSnlp).Ccsds.Apid()
		if err != nil {
			return 0, err
		}
		tmp12 = tmp14
	} else {
		tmp15, err := this.RoutingHeader.(*VoidProtocol_HeaderCcsds).Apid()
		if err != nil {
			return 0, err
		}
		tmp12 = tmp15
	}
	this.globalApid = int(tmp12)
	return this.globalApid, nil
}

/**
 * 0=Telemetry, 1=Command. valid for both SNLP and CCSDS.
 */
func (this *VoidProtocol) GlobalPacketType() (v int, err error) {
	if (this._f_globalPacketType) {
		return this.globalPacketType, nil
	}
	this._f_globalPacketType = true
	var tmp16 int;
	tmp17, err := this.IsSnlp()
	if err != nil {
		return 0, err
	}
	if (tmp17) {
		tmp18, err := this.RoutingHeader.(*VoidProtocol_HeaderSnlp).Ccsds.PacketType()
		if err != nil {
			return 0, err
		}
		tmp16 = tmp18
	} else {
		tmp19, err := this.RoutingHeader.(*VoidProtocol_HeaderCcsds).PacketType()
		if err != nil {
			return 0, err
		}
		tmp16 = tmp19
	}
	this.globalPacketType = int(tmp16)
	return this.globalPacketType, nil
}
func (this *VoidProtocol) IsSnlp() (v bool, err error) {
	if (this._f_isSnlp) {
		return this.isSnlp, nil
	}
	this._f_isSnlp = true
	tmp20, err := this.MagicPeek()
	if err != nil {
		return false, err
	}
	this.isSnlp = bool(tmp20 == 486647205)
	return this.isSnlp, nil
}
func (this *VoidProtocol) MagicPeek() (v uint32, err error) {
	if (this._f_magicPeek) {
		return this.magicPeek, nil
	}
	this._f_magicPeek = true
	_pos, err := this._io.Pos()
	if err != nil {
		return 0, err
	}
	_, err = this._io.Seek(int64(0), io.SeekStart)
	if err != nil {
		return 0, err
	}
	tmp21, err := this._io.ReadU4be()
	if err != nil {
		return 0, err
	}
	this.magicPeek = tmp21
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return 0, err
	}
	return this.magicPeek, nil
}
func (this *VoidProtocol) PayloadLen() (v int, err error) {
	if (this._f_payloadLen) {
		return this.payloadLen, nil
	}
	this._f_payloadLen = true
	var tmp22 int;
	tmp23, err := this.IsSnlp()
	if err != nil {
		return 0, err
	}
	if (tmp23) {
		tmp24, err := this._io.Size()
		if err != nil {
			return 0, err
		}
		tmp22 = tmp24 - 14
	} else {
		tmp25, err := this._io.Size()
		if err != nil {
			return 0, err
		}
		tmp22 = tmp25 - 6
	}
	this.payloadLen = int(tmp22)
	return this.payloadLen, nil
}
type VoidProtocol_Dispatch122 struct {
	Content kaitai.Struct
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_Dispatch122() *VoidProtocol_Dispatch122 {
	return &VoidProtocol_Dispatch122{
	}
}

func (this VoidProtocol_Dispatch122) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_Dispatch122) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp26, err := this._root.GlobalPacketType()
	if err != nil {
		return err
	}
	switch (tmp26) {
	case 0:
		tmp27 := NewVoidProtocol_PacketDBody()
		err = tmp27.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Content = tmp27
	case 1:
		tmp28 := NewVoidProtocol_PacketAckBody()
		err = tmp28.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Content = tmp28
	}
	return err
}

/**
 * CCSDS Primary Header - 6 Bytes
 * 
 * Standard CCSDS 133.0-B-2 Space Packet Header.
 *   - **Endianness:** Big-Endian (Network Byte Order).
 *   - **APID:** Used for local routing. Global identity is handled via `sat_id` in the payload.
 */
type VoidProtocol_HeaderCcsds struct {
	VersionTypeSecApid uint16
	SeqFlagsCount uint16
	PacketLength uint16
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent kaitai.Struct
	_f_actualLength bool
	actualLength int
	_f_apid bool
	apid int
	_f_packetType bool
	packetType int
	_f_secHeaderFlag bool
	secHeaderFlag int
	_f_seqCount bool
	seqCount int
	_f_seqFlags bool
	seqFlags int
	_f_version bool
	version int
}
func NewVoidProtocol_HeaderCcsds() *VoidProtocol_HeaderCcsds {
	return &VoidProtocol_HeaderCcsds{
	}
}

func (this VoidProtocol_HeaderCcsds) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_HeaderCcsds) Read(io *kaitai.Stream, parent kaitai.Struct, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp29, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.VersionTypeSecApid = uint16(tmp29)
	tmp30, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.SeqFlagsCount = uint16(tmp30)
	tmp31, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.PacketLength = uint16(tmp31)
	return err
}

/**
 * Total packet length in bytes (derived from CCSDS field)
 */
func (this *VoidProtocol_HeaderCcsds) ActualLength() (v int, err error) {
	if (this._f_actualLength) {
		return this.actualLength, nil
	}
	this._f_actualLength = true
	this.actualLength = int(this.PacketLength + 7)
	return this.actualLength, nil
}
func (this *VoidProtocol_HeaderCcsds) Apid() (v int, err error) {
	if (this._f_apid) {
		return this.apid, nil
	}
	this._f_apid = true
	this.apid = int(this.VersionTypeSecApid & 2047)
	return this.apid, nil
}

/**
 * 0=Telemetry (Packet D), 1=Command (Packet ACK)
 */
func (this *VoidProtocol_HeaderCcsds) PacketType() (v int, err error) {
	if (this._f_packetType) {
		return this.packetType, nil
	}
	this._f_packetType = true
	this.packetType = int((this.VersionTypeSecApid >> 12) & 1)
	return this.packetType, nil
}
func (this *VoidProtocol_HeaderCcsds) SecHeaderFlag() (v int, err error) {
	if (this._f_secHeaderFlag) {
		return this.secHeaderFlag, nil
	}
	this._f_secHeaderFlag = true
	this.secHeaderFlag = int((this.VersionTypeSecApid >> 11) & 1)
	return this.secHeaderFlag, nil
}
func (this *VoidProtocol_HeaderCcsds) SeqCount() (v int, err error) {
	if (this._f_seqCount) {
		return this.seqCount, nil
	}
	this._f_seqCount = true
	this.seqCount = int(this.SeqFlagsCount & 1023)
	return this.seqCount, nil
}
func (this *VoidProtocol_HeaderCcsds) SeqFlags() (v int, err error) {
	if (this._f_seqFlags) {
		return this.seqFlags, nil
	}
	this._f_seqFlags = true
	this.seqFlags = int((this.SeqFlagsCount >> 14) & 3)
	return this.seqFlags, nil
}
func (this *VoidProtocol_HeaderCcsds) Version() (v int, err error) {
	if (this._f_version) {
		return this.version, nil
	}
	this._f_version = true
	this.version = int((this.VersionTypeSecApid >> 13) & 7)
	return this.version, nil
}

/**
 * Space Network Layer Protocol (SNLP) Header - 14 Bytes
 * 
 * Designed for asynchronous, low-bandwidth LoRa links.
 * Structure:
 *   - **Sync Word (4B):** `0x1D01A5A5` for frame detection in noise.
 *   - **CCSDS (6B):** Standard space packet identity.
 *   - **Alignment Pad (4B):** Ensures the payload starts at a 64-bit aligned memory address.
 */
type VoidProtocol_HeaderSnlp struct {
	SyncWord []byte
	Ccsds *VoidProtocol_HeaderCcsds
	AlignPad []byte
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_HeaderSnlp() *VoidProtocol_HeaderSnlp {
	return &VoidProtocol_HeaderSnlp{
	}
}

func (this VoidProtocol_HeaderSnlp) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_HeaderSnlp) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp32, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp32 = tmp32
	this.SyncWord = tmp32
	if !(bytes.Equal(this.SyncWord, []uint8{29, 1, 165, 165})) {
		return kaitai.NewValidationNotEqualError([]uint8{29, 1, 165, 165}, this.SyncWord, this._io, "/types/header_snlp/seq/0")
	}
	tmp33 := NewVoidProtocol_HeaderCcsds()
	err = tmp33.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Ccsds = tmp33
	tmp34, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp34 = tmp34
	this.AlignPad = tmp34
	return err
}

/**
 * Community Sync Word (LoRa)
 */

/**
 * 4-Byte Pad for 64-bit Alignment
 */

/**
 * System Heartbeat (Health & Status & GPS)
 */
type VoidProtocol_HeartbeatBody struct {
	EpochTs uint64
	VbattMv uint16
	TempC int16
	PressurePa uint32
	SysState uint8
	SatLock uint8
	LatFixed int32
	LonFixed int32
	ReservedInterval []byte
	GpsSpeedCms uint16
	Crc32 uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_HeartbeatBody() *VoidProtocol_HeartbeatBody {
	return &VoidProtocol_HeartbeatBody{
	}
}

func (this VoidProtocol_HeartbeatBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_HeartbeatBody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp35, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.EpochTs = uint64(tmp35)
	tmp36, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.VbattMv = uint16(tmp36)
	tmp37, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.TempC = int16(tmp37)
	tmp38, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PressurePa = uint32(tmp38)
	tmp39, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SysState = tmp39
	tmp40, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SatLock = tmp40
	tmp41, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.LatFixed = int32(tmp41)
	tmp42, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.LonFixed = int32(tmp42)
	tmp43, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp43 = tmp43
	this.ReservedInterval = tmp43
	tmp44, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.GpsSpeedCms = uint16(tmp44)
	tmp45, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp45)
	return err
}

/**
 * Timestamp (Unix)
 */

/**
 * Battery Voltage (mV)
 */

/**
 * Internal Temp (Centidegrees, e.g. 2500 = 25.00C)
 */

/**
 * Barometric Pressure (Pascals)
 */

/**
 * State Machine ID (0=Boot, 1=Idle, 2=Tx...)
 */

/**
 * GPS Satellite Count
 */

/**
 * Latitude (Scaled by 10^7, e.g. 51500000 = 51.5N)
 */

/**
 * Longitude (Scaled by 10^7, e.g. -120000 = 0.12W)
 */

/**
 * Reserved for 2026 payload expansion
 */

/**
 * Ground Speed (cm/s, e.g. 540 = 5.4 m/s)
 */

/**
 * The Invoice (62 Bytes Payload)
 */
type VoidProtocol_PacketABody struct {
	EpochTs uint64
	PosVec *VoidProtocol_Vector3d
	VelVec *VoidProtocol_Vector3f
	SatId uint32
	Amount uint64
	AssetId uint16
	Crc32 uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketABody() *VoidProtocol_PacketABody {
	return &VoidProtocol_PacketABody{
	}
}

func (this VoidProtocol_PacketABody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketABody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp46, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.EpochTs = uint64(tmp46)
	tmp47 := NewVoidProtocol_Vector3d()
	err = tmp47.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PosVec = tmp47
	tmp48 := NewVoidProtocol_Vector3f()
	err = tmp48.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.VelVec = tmp48
	tmp49, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SatId = uint32(tmp49)
	tmp50, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.Amount = uint64(tmp50)
	tmp51, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.AssetId = uint16(tmp51)
	tmp52, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp52)
	return err
}

/**
 * Packet ACK: Ground Station Command
 * 
 * Uplink packet containing Relay Instructions and the 'Unlock' key.
 * 
 * ## Tunnel Data Sizing
 * The `enc_tunnel` field varies in size to maintain alignment:
 * - **SNLP:** 96 Bytes (Includes 14B SNLP Header internally).
 * - **CCSDS:** 88 Bytes (Standard 6B Header).
 */
type VoidProtocol_PacketAckBody struct {
	PadA []byte
	TargetTxId uint32
	Status uint8
	PadB []byte
	RelayOps *VoidProtocol_RelayOpsT
	EncTunnel []byte
	PadC []byte
	Crc32 uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent kaitai.Struct
}
func NewVoidProtocol_PacketAckBody() *VoidProtocol_PacketAckBody {
	return &VoidProtocol_PacketAckBody{
	}
}

func (this VoidProtocol_PacketAckBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketAckBody) Read(io *kaitai.Stream, parent kaitai.Struct, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp53, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp53 = tmp53
	this.PadA = tmp53
	tmp54, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TargetTxId = uint32(tmp54)
	tmp55, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Status = tmp55
	tmp56, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp56 = tmp56
	this.PadB = tmp56
	tmp57 := NewVoidProtocol_RelayOpsT()
	err = tmp57.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.RelayOps = tmp57
	var tmp58 int8;
	tmp59, err := this._root.IsSnlp()
	if err != nil {
		return err
	}
	if (tmp59) {
		tmp58 = 96
	} else {
		tmp58 = 88
	}
	tmp60, err := this._io.ReadBytes(int(tmp58))
	if err != nil {
		return err
	}
	tmp60 = tmp60
	this.EncTunnel = tmp60
	tmp61, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp61 = tmp61
	this.PadC = tmp61
	tmp62, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp62)
	return err
}

/**
 * SNLP=96B (Full Header), CCSDS=88B (Compact Header)
 */

/**
 * Packet B: The Encrypted Payment
 * 
 * Encapsulated payment intent sent by Sat B (Mule) to the Ground Station.
 * 
 * ## Encryption Logic
 * - **Enterprise (CCSDS):** Payload is ChaCha20 Poly1305 Encrypted.
 * - **Community (SNLP):** Payload is PLAINTEXT to comply with TinyGS/Amateur radio regulations.
 */
type VoidProtocol_PacketBBody struct {
	EpochTs uint64
	PosVec *VoidProtocol_Vector3d
	EncPayload []byte
	SatId uint32
	Nonce uint32
	Signature []byte
	GlobalCrc uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketBBody() *VoidProtocol_PacketBBody {
	return &VoidProtocol_PacketBBody{
	}
}

func (this VoidProtocol_PacketBBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketBBody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp63, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.EpochTs = uint64(tmp63)
	tmp64 := NewVoidProtocol_Vector3d()
	err = tmp64.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PosVec = tmp64
	tmp65, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp65 = tmp65
	this.EncPayload = tmp65
	tmp66, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SatId = uint32(tmp66)
	tmp67, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Nonce = uint32(tmp67)
	tmp68, err := this._io.ReadBytes(int(64))
	if err != nil {
		return err
	}
	tmp68 = tmp68
	this.Signature = tmp68
	tmp69, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GlobalCrc = uint32(tmp69)
	return err
}

/**
 * Sat B Position Vector (X, Y, Z)
 */

/**
 * Inner Invoice. Plaintext if SNLP (Public), ChaCha20 Ciphertext if CCSDS (Private).
 */

/**
 * Packet C: The Receipt (Proof of Execution)
 * 
 * Generated by Sat A (Seller) after a successful service dispensation.
 * Contains the cryptographic signature linking the service to the original payment nonce.
 */
type VoidProtocol_PacketCBody struct {
	PadHead []byte
	ExecTime uint64
	EncTxId uint64
	EncStatus uint8
	PadSig []byte
	Signature []byte
	Crc32 uint32
	TailPad []byte
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketCBody() *VoidProtocol_PacketCBody {
	return &VoidProtocol_PacketCBody{
	}
}

func (this VoidProtocol_PacketCBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketCBody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp70, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp70 = tmp70
	this.PadHead = tmp70
	tmp71, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.ExecTime = uint64(tmp71)
	tmp72, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.EncTxId = uint64(tmp72)
	tmp73, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.EncStatus = tmp73
	tmp74, err := this._io.ReadBytes(int(7))
	if err != nil {
		return err
	}
	tmp74 = tmp74
	this.PadSig = tmp74
	tmp75, err := this._io.ReadBytes(int(64))
	if err != nil {
		return err
	}
	tmp75 = tmp75
	this.Signature = tmp75
	tmp76, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp76)
	tmp77, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp77 = tmp77
	this.TailPad = tmp77
	return err
}

/**
 * Packet D: The Delivery
 * 
 * A transport wrapper used by Sat B (Mule) to downlink Packet C to the ground.
 * This packet wraps the receipt in a new CCSDS/SNLP frame for radio transmission.
 */
type VoidProtocol_PacketDBody struct {
	PadHead []byte
	DownlinkTs uint64
	SatBId uint32
	Payload []byte
	GlobalCrc uint32
	Tail []byte
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol_Dispatch122
}
func NewVoidProtocol_PacketDBody() *VoidProtocol_PacketDBody {
	return &VoidProtocol_PacketDBody{
	}
}

func (this VoidProtocol_PacketDBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketDBody) Read(io *kaitai.Stream, parent *VoidProtocol_Dispatch122, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp78, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp78 = tmp78
	this.PadHead = tmp78
	tmp79, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.DownlinkTs = uint64(tmp79)
	tmp80, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SatBId = uint32(tmp80)
	tmp81, err := this._io.ReadBytes(int(98))
	if err != nil {
		return err
	}
	tmp81 = tmp81
	this.Payload = tmp81
	tmp82, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GlobalCrc = uint32(tmp82)
	tmp83, err := this._io.ReadBytes(int(6))
	if err != nil {
		return err
	}
	tmp83 = tmp83
	this.Tail = tmp83
	return err
}

/**
 * Ephemeral Key Exchange (106 Bytes Payload)
 */
type VoidProtocol_PacketHBody struct {
	SessionTtl uint16
	Timestamp uint64
	EphPubKey []byte
	Signature []byte
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketHBody() *VoidProtocol_PacketHBody {
	return &VoidProtocol_PacketHBody{
	}
}

func (this VoidProtocol_PacketHBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketHBody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp84, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.SessionTtl = uint16(tmp84)
	tmp85, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.Timestamp = uint64(tmp85)
	tmp86, err := this._io.ReadBytes(int(32))
	if err != nil {
		return err
	}
	tmp86 = tmp86
	this.EphPubKey = tmp86
	tmp87, err := this._io.ReadBytes(int(64))
	if err != nil {
		return err
	}
	tmp87 = tmp87
	this.Signature = tmp87
	return err
}
type VoidProtocol_RelayOpsT struct {
	Azimuth uint16
	Elevation uint16
	Frequency uint32
	DurationMs uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol_PacketAckBody
}
func NewVoidProtocol_RelayOpsT() *VoidProtocol_RelayOpsT {
	return &VoidProtocol_RelayOpsT{
	}
}

func (this VoidProtocol_RelayOpsT) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_RelayOpsT) Read(io *kaitai.Stream, parent *VoidProtocol_PacketAckBody, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp88, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Azimuth = uint16(tmp88)
	tmp89, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Elevation = uint16(tmp89)
	tmp90, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Frequency = uint32(tmp90)
	tmp91, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DurationMs = uint32(tmp91)
	return err
}

/**
 * IEEE 754 Double Precision Vector (X, Y, Z)
 */
type VoidProtocol_Vector3d struct {
	X float64
	Y float64
	Z float64
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent kaitai.Struct
}
func NewVoidProtocol_Vector3d() *VoidProtocol_Vector3d {
	return &VoidProtocol_Vector3d{
	}
}

func (this VoidProtocol_Vector3d) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_Vector3d) Read(io *kaitai.Stream, parent kaitai.Struct, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp92, err := this._io.ReadF8le()
	if err != nil {
		return err
	}
	this.X = float64(tmp92)
	tmp93, err := this._io.ReadF8le()
	if err != nil {
		return err
	}
	this.Y = float64(tmp93)
	tmp94, err := this._io.ReadF8le()
	if err != nil {
		return err
	}
	this.Z = float64(tmp94)
	return err
}

/**
 * ECEF X Coordinate (Meters)
 */

/**
 * ECEF Y Coordinate (Meters)
 */

/**
 * ECEF Z Coordinate (Meters)
 */

/**
 * IEEE 754 Single Precision Vector (dX, dY, dZ)
 */
type VoidProtocol_Vector3f struct {
	X float32
	Y float32
	Z float32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol_PacketABody
}
func NewVoidProtocol_Vector3f() *VoidProtocol_Vector3f {
	return &VoidProtocol_Vector3f{
	}
}

func (this VoidProtocol_Vector3f) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_Vector3f) Read(io *kaitai.Stream, parent *VoidProtocol_PacketABody, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp95, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.X = float32(tmp95)
	tmp96, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Y = float32(tmp96)
	tmp97, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Z = float32(tmp97)
	return err
}
