// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package protocol

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

/**
 * Strict implementation of CCSDS 133.0-B-2 Section 4.1.3.
 *
 * 6-octet Primary Header. Big-Endian (Network Byte Order).
 * Self-delimiting via the Packet Data Length field.
 *
 * Bit Layout:
 *   [0-2]   Version Number     3 bits   MUST be 000
 *   [3]     Packet Type        1 bit    0=TM, 1=TC
 *   [4]     Sec Header Flag    1 bit    1=Present
 *   [5-15]  APID               11 bits  0x000-0x7FF
 *   [16-17] Sequence Flags     2 bits   11=Unsegmented
 *   [18-31] Sequence Count     14 bits  0-16383
 *   [32-47] Packet Data Length 16 bits  (N-1) octets
 *
 * This module is transport-agnostic and reusable across any
 * CCSDS-compliant project. It owns ONLY the 6-byte header.
 */
type CcsdsPrimaryHeader struct {
	VersionTypeFlagApid  uint16
	SeqFlagsCount        uint16
	PacketDataLength     uint16
	_io                  *kaitai.Stream
	_root                *CcsdsPrimaryHeader
	_parent              kaitai.Struct
	_f_apid              bool
	apid                 int
	_f_dataFieldLength   bool
	dataFieldLength      int
	_f_packetType        bool
	packetType           int
	_f_secHeaderFlag     bool
	secHeaderFlag        int
	_f_seqCount          bool
	seqCount             int
	_f_seqFlags          bool
	seqFlags             int
	_f_totalPacketLength bool
	totalPacketLength    int
	_f_version           bool
	version              int
}

func NewCcsdsPrimaryHeader() *CcsdsPrimaryHeader {
	return &CcsdsPrimaryHeader{}
}

func (this CcsdsPrimaryHeader) IO_() *kaitai.Stream {
	return this._io
}

func (this *CcsdsPrimaryHeader) Read(io *kaitai.Stream, parent kaitai.Struct, root *CcsdsPrimaryHeader) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.VersionTypeFlagApid = uint16(tmp1)
	tmp2, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.SeqFlagsCount = uint16(tmp2)
	tmp3, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.PacketDataLength = uint16(tmp3)
	return err
}

/**
 * 11-bit Application Process Identifier (0-2047).
 */
func (this *CcsdsPrimaryHeader) Apid() (v int, err error) {
	if this._f_apid {
		return this.apid, nil
	}
	this._f_apid = true
	this.apid = int(this.VersionTypeFlagApid & 2047)
	return this.apid, nil
}

/**
 * Actual octets in Packet Data Field.
 */
func (this *CcsdsPrimaryHeader) DataFieldLength() (v int, err error) {
	if this._f_dataFieldLength {
		return this.dataFieldLength, nil
	}
	this._f_dataFieldLength = true
	this.dataFieldLength = int(this.PacketDataLength + 1)
	return this.dataFieldLength, nil
}

/**
 * 0=Telemetry (TM), 1=Telecommand (TC).
 */
func (this *CcsdsPrimaryHeader) PacketType() (v int, err error) {
	if this._f_packetType {
		return this.packetType, nil
	}
	this._f_packetType = true
	this.packetType = int((this.VersionTypeFlagApid >> 12) & 1)
	return this.packetType, nil
}

/**
 * 1=Secondary Header present in Packet Data Field.
 */
func (this *CcsdsPrimaryHeader) SecHeaderFlag() (v int, err error) {
	if this._f_secHeaderFlag {
		return this.secHeaderFlag, nil
	}
	this._f_secHeaderFlag = true
	this.secHeaderFlag = int((this.VersionTypeFlagApid >> 11) & 1)
	return this.secHeaderFlag, nil
}

/**
 * 14-bit Packet Sequence Count (0-16383).
 * HARDENED: Mask is 0x3FFF (14 bits).
 * Previous version used 0x3FF (10 bits) — CRITICAL BUG.
 */
func (this *CcsdsPrimaryHeader) SeqCount() (v int, err error) {
	if this._f_seqCount {
		return this.seqCount, nil
	}
	this._f_seqCount = true
	this.seqCount = int(this.SeqFlagsCount & 16383)
	return this.seqCount, nil
}

/**
 * 00=Continuation, 01=First, 10=Last, 11=Unsegmented.
 */
func (this *CcsdsPrimaryHeader) SeqFlags() (v int, err error) {
	if this._f_seqFlags {
		return this.seqFlags, nil
	}
	this._f_seqFlags = true
	this.seqFlags = int((this.SeqFlagsCount >> 14) & 3)
	return this.seqFlags, nil
}

/**
 * Total packet size in octets = 6 (header) + data_field_length.
 */
func (this *CcsdsPrimaryHeader) TotalPacketLength() (v int, err error) {
	if this._f_totalPacketLength {
		return this.totalPacketLength, nil
	}
	this._f_totalPacketLength = true
	this.totalPacketLength = int(this.PacketDataLength + 7)
	return this.totalPacketLength, nil
}

/**
 * 3-bit Version Number. MUST be 0 (CCSDS Version 1 per CCSDS 133.0-B-2
 * §4.1.3.1). Non-zero indicates an unknown future revision and MUST be
 * rejected by the ingest handler. Enforced application-side — kaitai
 * `valid:` is unsupported on instance fields.
 */
func (this *CcsdsPrimaryHeader) Version() (v int, err error) {
	if this._f_version {
		return this.version, nil
	}
	this._f_version = true
	this.version = int((this.VersionTypeFlagApid >> 13) & 7)
	return this.version, nil
}

/**
 * Word 0: Version(3) + Type(1) + SecHdrFlag(1) + APID(11)
 */

/**
 * Word 1: SeqFlags(2) + SeqCount(14)
 */

/**
 * Word 2: Packet Data Field Length minus 1
 */
