// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package protocol

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Reusable field types and enumerations for all VOP packet bodies.
 * 
 * All types in this module are Little-Endian (payload convention).
 * Import this module into any packet body definition that uses
 * vectors, signatures, or protocol-defined enumerations.
 */

type TigCommonTypes_AssetId int
const (
	TigCommonTypes_AssetId__Usdc TigCommonTypes_AssetId = 1
)
var values_TigCommonTypes_AssetId = map[TigCommonTypes_AssetId]struct{}{1: {}}
func (v TigCommonTypes_AssetId) isDefined() bool {
	_, ok := values_TigCommonTypes_AssetId[v]
	return ok
}

type TigCommonTypes_CmdCode int
const (
	TigCommonTypes_CmdCode__UnlockDispense TigCommonTypes_CmdCode = 1
	TigCommonTypes_CmdCode__AtomicDestroy TigCommonTypes_CmdCode = 255
)
var values_TigCommonTypes_CmdCode = map[TigCommonTypes_CmdCode]struct{}{1: {}, 255: {}}
func (v TigCommonTypes_CmdCode) isDefined() bool {
	_, ok := values_TigCommonTypes_CmdCode[v]
	return ok
}

type TigCommonTypes_PacketTypeId int
const (
	TigCommonTypes_PacketTypeId__Telemetry TigCommonTypes_PacketTypeId = 0
	TigCommonTypes_PacketTypeId__Telecommand TigCommonTypes_PacketTypeId = 1
)
var values_TigCommonTypes_PacketTypeId = map[TigCommonTypes_PacketTypeId]struct{}{0: {}, 1: {}}
func (v TigCommonTypes_PacketTypeId) isDefined() bool {
	_, ok := values_TigCommonTypes_PacketTypeId[v]
	return ok
}

type TigCommonTypes_SettlementStatus int
const (
	TigCommonTypes_SettlementStatus__Settled TigCommonTypes_SettlementStatus = 1
	TigCommonTypes_SettlementStatus__Rejected TigCommonTypes_SettlementStatus = 255
)
var values_TigCommonTypes_SettlementStatus = map[TigCommonTypes_SettlementStatus]struct{}{1: {}, 255: {}}
func (v TigCommonTypes_SettlementStatus) isDefined() bool {
	_, ok := values_TigCommonTypes_SettlementStatus[v]
	return ok
}

type TigCommonTypes_SysState int
const (
	TigCommonTypes_SysState__Boot TigCommonTypes_SysState = 0
	TigCommonTypes_SysState__Idle TigCommonTypes_SysState = 1
	TigCommonTypes_SysState__TxActive TigCommonTypes_SysState = 2
	TigCommonTypes_SysState__RxActive TigCommonTypes_SysState = 3
	TigCommonTypes_SysState__Connected TigCommonTypes_SysState = 4
	TigCommonTypes_SysState__Provisioning TigCommonTypes_SysState = 5
	TigCommonTypes_SysState__Error TigCommonTypes_SysState = 6
)
var values_TigCommonTypes_SysState = map[TigCommonTypes_SysState]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}}
func (v TigCommonTypes_SysState) isDefined() bool {
	_, ok := values_TigCommonTypes_SysState[v]
	return ok
}
type TigCommonTypes struct {
	_io *kaitai.Stream
	_root *TigCommonTypes
	_parent kaitai.Struct
}
func NewTigCommonTypes() *TigCommonTypes {
	return &TigCommonTypes{
	}
}

func (this TigCommonTypes) IO_() *kaitai.Stream {
	return this._io
}

func (this *TigCommonTypes) Read(io *kaitai.Stream, parent kaitai.Struct, root *TigCommonTypes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}

/**
 * 64-byte Ed25519 / PUF Identity Signature.
 * Opaque blob — no internal structure parsed.
 * Verification is performed by the application layer,
 * not the binary parser.
 */
type TigCommonTypes_Ed25519Signature struct {
	Raw []byte
	_io *kaitai.Stream
	_root *TigCommonTypes
	_parent kaitai.Struct
}
func NewTigCommonTypes_Ed25519Signature() *TigCommonTypes_Ed25519Signature {
	return &TigCommonTypes_Ed25519Signature{
	}
}

func (this TigCommonTypes_Ed25519Signature) IO_() *kaitai.Stream {
	return this._io
}

func (this *TigCommonTypes_Ed25519Signature) Read(io *kaitai.Stream, parent kaitai.Struct, root *TigCommonTypes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(64))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Raw = tmp1
	return err
}

/**
 * GPS coordinates in fixed-point representation.
 * Scaled by 10^7 (e.g., 515000000 = 51.5000000 degrees N).
 * Signed: negative = South/West.
 */
type TigCommonTypes_GpsFixedPoint struct {
	Latitude int32
	Longitude int32
	_io *kaitai.Stream
	_root *TigCommonTypes
	_parent kaitai.Struct
}
func NewTigCommonTypes_GpsFixedPoint() *TigCommonTypes_GpsFixedPoint {
	return &TigCommonTypes_GpsFixedPoint{
	}
}

func (this TigCommonTypes_GpsFixedPoint) IO_() *kaitai.Stream {
	return this._io
}

func (this *TigCommonTypes_GpsFixedPoint) Read(io *kaitai.Stream, parent kaitai.Struct, root *TigCommonTypes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp2, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Latitude = int32(tmp2)
	tmp3, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Longitude = int32(tmp3)
	return err
}

/**
 * Latitude * 10^7
 */

/**
 * Longitude * 10^7
 */

/**
 * 12-byte Relay Operations Sub-structure.
 * Used by Sat B to orient transmission toward Sat A.
 * All fields Little-Endian.
 */
type TigCommonTypes_RelayOps struct {
	Azimuth uint16
	Elevation uint16
	Frequency uint32
	DurationMs uint32
	_io *kaitai.Stream
	_root *TigCommonTypes
	_parent kaitai.Struct
}
func NewTigCommonTypes_RelayOps() *TigCommonTypes_RelayOps {
	return &TigCommonTypes_RelayOps{
	}
}

func (this TigCommonTypes_RelayOps) IO_() *kaitai.Stream {
	return this._io
}

func (this *TigCommonTypes_RelayOps) Read(io *kaitai.Stream, parent kaitai.Struct, root *TigCommonTypes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp4, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Azimuth = uint16(tmp4)
	tmp5, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Elevation = uint16(tmp5)
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Frequency = uint32(tmp6)
	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.DurationMs = uint32(tmp7)
	return err
}

/**
 * Horizontal Look Angle (degrees * scale factor)
 */

/**
 * Vertical Look Angle (degrees * scale factor)
 */

/**
 * Target Tx Frequency in Hz
 */

/**
 * Relay Window duration in milliseconds
 */

/**
 * IEEE 754 Double-Precision 3D Position Vector (24 bytes).
 * ECEF Coordinates in meters. Little-Endian.
 * Alignment: Each f8 sits on natural 8-byte boundary when
 * the vector starts on an 8-byte aligned offset.
 */
type TigCommonTypes_Vector3d struct {
	X float64
	Y float64
	Z float64
	_io *kaitai.Stream
	_root *TigCommonTypes
	_parent kaitai.Struct
}
func NewTigCommonTypes_Vector3d() *TigCommonTypes_Vector3d {
	return &TigCommonTypes_Vector3d{
	}
}

func (this TigCommonTypes_Vector3d) IO_() *kaitai.Stream {
	return this._io
}

func (this *TigCommonTypes_Vector3d) Read(io *kaitai.Stream, parent kaitai.Struct, root *TigCommonTypes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp8, err := this._io.ReadF8le()
	if err != nil {
		return err
	}
	this.X = float64(tmp8)
	tmp9, err := this._io.ReadF8le()
	if err != nil {
		return err
	}
	this.Y = float64(tmp9)
	tmp10, err := this._io.ReadF8le()
	if err != nil {
		return err
	}
	this.Z = float64(tmp10)
	return err
}

/**
 * ECEF X Coordinate (meters)
 */

/**
 * ECEF Y Coordinate (meters)
 */

/**
 * ECEF Z Coordinate (meters)
 */

/**
 * IEEE 754 Single-Precision 3D Velocity Vector (12 bytes).
 * Derivative components (dX, dY, dZ). Little-Endian.
 */
type TigCommonTypes_Vector3f struct {
	X float32
	Y float32
	Z float32
	_io *kaitai.Stream
	_root *TigCommonTypes
	_parent kaitai.Struct
}
func NewTigCommonTypes_Vector3f() *TigCommonTypes_Vector3f {
	return &TigCommonTypes_Vector3f{
	}
}

func (this TigCommonTypes_Vector3f) IO_() *kaitai.Stream {
	return this._io
}

func (this *TigCommonTypes_Vector3f) Read(io *kaitai.Stream, parent kaitai.Struct, root *TigCommonTypes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp11, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.X = float32(tmp11)
	tmp12, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Y = float32(tmp12)
	tmp13, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Z = float32(tmp13)
	return err
}

/**
 * dX velocity component
 */

/**
 * dY velocity component
 */

/**
 * dZ velocity component
 */

/**
 * 32-byte X25519 Ephemeral Public Key for ECDH.
 */
type TigCommonTypes_X25519PublicKey struct {
	Raw []byte
	_io *kaitai.Stream
	_root *TigCommonTypes
	_parent kaitai.Struct
}
func NewTigCommonTypes_X25519PublicKey() *TigCommonTypes_X25519PublicKey {
	return &TigCommonTypes_X25519PublicKey{
	}
}

func (this TigCommonTypes_X25519PublicKey) IO_() *kaitai.Stream {
	return this._io
}

func (this *TigCommonTypes_X25519PublicKey) Read(io *kaitai.Stream, parent kaitai.Struct, root *TigCommonTypes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp14, err := this._io.ReadBytes(int(32))
	if err != nil {
		return err
	}
	tmp14 = tmp14
	this.Raw = tmp14
	return err
}
