// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package protocol

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"io"
)


/**
 * -------------------------------------------------------------------------
 * VOID PROTOCOL v2.1 | Tiny Innovation Group Ltd — HARDENED
 * -------------------------------------------------------------------------
 * Authority: Tiny Innovation Group Ltd
 * License:   Apache-2.0
 * Status:    Hardened / Audit-Remediated
 * 
 * CHANGES FROM v2.0 (Pre-Audit):
 *   C-01 FIX: seq_count mask corrected to 0x3FFF (14-bit).
 *   F-01 FIX: SNLP header locked at 14B (Option B, VOID-113/114B).
 *             snlp_header.ksy align_pad = 4 bytes. See Protocol-spec-SNLP.md
 *             § 1-2 and VOID_114_SNLP_HEADER_ALIGNMENT_DECISION_2026-04-14.md.
 *   F-02 FIX: Body dispatch uses CCSDS packet_data_length, not _io.size.
 *   F-03 FIX: dispatch_122 switches on `magic` byte at body offset 0
 *             (0xD0 = Packet D, 0xAC = Packet ACK). Replaces single-bit
 *             CCSDS Type-bit trust with an 8-bit Hamming-distance-4
 *             discriminant. Absorbed from existing pad bytes — zero
 *             impact on frame totals or downstream alignment.
 *   F-04 FIX: Packet ACK split into SNLP/CCSDS variants (fixed tunnel size).
 *   K-01 FIX: Modularized via imports.
 *   K-02 FIX: Enums defined in tig_common_types.
 *   K-03 FIX: valid constraints on CCSDS version, sync word, alignment pads.
 *   K-04 FIX: doc-ref converted to YAML list.
 * 
 * OPEN ITEMS: none.
 * @see <a href="https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/docs/Acknowledgment-spec.md">Source</a>
 * @see <a href="https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/docs/Protocol-spec-CCSDS.md">Source</a>
 * @see <a href="https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/docs/Protocol-spec-SNLP.md">Source</a>
 * @see <a href="https://github.com/Tiny-Innovations-Group/void-protocol-oss/blob/main/docs/Receipt-spec.md">Source</a>
 */
type VoidProtocol struct {
	RoutingHeader kaitai.Struct
	Body interface{}
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent kaitai.Struct
	_raw_Body []byte
	_f_bodyLength bool
	bodyLength int
	_f_globalApid bool
	globalApid int
	_f_globalPacketType bool
	globalPacketType int
	_f_isSnlp bool
	isSnlp bool
	_f_magicPeek bool
	magicPeek uint32
}
func NewVoidProtocol() *VoidProtocol {
	return &VoidProtocol{
	}
}

func (this VoidProtocol) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol) Read(io *kaitai.Stream, parent kaitai.Struct, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._root.IsSnlp()
	if err != nil {
		return err
	}
	switch (tmp1) {
	case false:
		tmp2 := NewCcsdsPrimaryHeader()
		err = tmp2.Read(this._io, nil, nil)
		if err != nil {
			return err
		}
		this.RoutingHeader = tmp2
	case true:
		tmp3 := NewSnlpHeader()
		err = tmp3.Read(this._io, nil, nil)
		if err != nil {
			return err
		}
		this.RoutingHeader = tmp3
	}
	tmp4, err := this._root.BodyLength()
	if err != nil {
		return err
	}
	switch (tmp4) {
	case 106:
		tmp5, err := this._root.BodyLength()
		if err != nil {
			return err
		}
		tmp6, err := this._io.ReadBytes(int(tmp5))
		if err != nil {
			return err
		}
		tmp6 = tmp6
		this._raw_Body = tmp6
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp7 := NewVoidProtocol_PacketHBody()
		err = tmp7.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp7
	case 114:
		tmp8, err := this._root.BodyLength()
		if err != nil {
			return err
		}
		tmp9, err := this._io.ReadBytes(int(tmp8))
		if err != nil {
			return err
		}
		tmp9 = tmp9
		this._raw_Body = tmp9
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp10 := NewVoidProtocol_PacketAckBodyCcsds()
		err = tmp10.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp10
	case 122:
		tmp11, err := this._root.BodyLength()
		if err != nil {
			return err
		}
		tmp12, err := this._io.ReadBytes(int(tmp11))
		if err != nil {
			return err
		}
		tmp12 = tmp12
		this._raw_Body = tmp12
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp13 := NewVoidProtocol_Dispatch122()
		err = tmp13.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp13
	case 178:
		tmp14, err := this._root.BodyLength()
		if err != nil {
			return err
		}
		tmp15, err := this._io.ReadBytes(int(tmp14))
		if err != nil {
			return err
		}
		tmp15 = tmp15
		this._raw_Body = tmp15
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp16 := NewVoidProtocol_PacketBBody()
		err = tmp16.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp16
	case 34:
		tmp17, err := this._root.BodyLength()
		if err != nil {
			return err
		}
		tmp18, err := this._io.ReadBytes(int(tmp17))
		if err != nil {
			return err
		}
		tmp18 = tmp18
		this._raw_Body = tmp18
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp19 := NewVoidProtocol_HeartbeatBody()
		err = tmp19.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp19
	case 66:
		tmp20, err := this._root.BodyLength()
		if err != nil {
			return err
		}
		tmp21, err := this._io.ReadBytes(int(tmp20))
		if err != nil {
			return err
		}
		tmp21 = tmp21
		this._raw_Body = tmp21
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp22 := NewVoidProtocol_PacketABody()
		err = tmp22.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp22
	case 98:
		tmp23, err := this._root.BodyLength()
		if err != nil {
			return err
		}
		tmp24, err := this._io.ReadBytes(int(tmp23))
		if err != nil {
			return err
		}
		tmp24 = tmp24
		this._raw_Body = tmp24
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp25 := NewVoidProtocol_PacketCBody()
		err = tmp25.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp25
	default:
		tmp26, err := this._root.BodyLength()
		if err != nil {
			return err
		}
		tmp27, err := this._io.ReadBytes(int(tmp26))
		if err != nil {
			return err
		}
		tmp27 = tmp27
		this._raw_Body = tmp27
	}
	return err
}

/**
 * Payload body length in octets. Derived from the CCSDS
 * packet_data_length field (SNLP override applied — the length
 * field excludes the full 14B SNLP header). Stream-safe: does
 * not depend on _io.size.
 */
func (this *VoidProtocol) BodyLength() (v int, err error) {
	if (this._f_bodyLength) {
		return this.bodyLength, nil
	}
	this._f_bodyLength = true
	var tmp28 int;
	tmp29, err := this.IsSnlp()
	if err != nil {
		return 0, err
	}
	if (tmp29) {
		tmp30, err := this.RoutingHeader.(*SnlpHeader).Ccsds.DataFieldLength()
		if err != nil {
			return 0, err
		}
		tmp28 = tmp30
	} else {
		tmp31, err := this.RoutingHeader.(*CcsdsPrimaryHeader).DataFieldLength()
		if err != nil {
			return 0, err
		}
		tmp28 = tmp31
	}
	this.bodyLength = int(tmp28)
	return this.bodyLength, nil
}

/**
 * 11-bit APID. Local routing only; global ID is sat_id in payload.
 */
func (this *VoidProtocol) GlobalApid() (v int, err error) {
	if (this._f_globalApid) {
		return this.globalApid, nil
	}
	this._f_globalApid = true
	var tmp32 int;
	tmp33, err := this.IsSnlp()
	if err != nil {
		return 0, err
	}
	if (tmp33) {
		tmp34, err := this.RoutingHeader.(*SnlpHeader).Ccsds.Apid()
		if err != nil {
			return 0, err
		}
		tmp32 = tmp34
	} else {
		tmp35, err := this.RoutingHeader.(*CcsdsPrimaryHeader).Apid()
		if err != nil {
			return 0, err
		}
		tmp32 = tmp35
	}
	this.globalApid = int(tmp32)
	return this.globalApid, nil
}

/**
 * 0=Telemetry, 1=Telecommand. Sourced from CCSDS header.
 */
func (this *VoidProtocol) GlobalPacketType() (v int, err error) {
	if (this._f_globalPacketType) {
		return this.globalPacketType, nil
	}
	this._f_globalPacketType = true
	var tmp36 int;
	tmp37, err := this.IsSnlp()
	if err != nil {
		return 0, err
	}
	if (tmp37) {
		tmp38, err := this.RoutingHeader.(*SnlpHeader).Ccsds.PacketType()
		if err != nil {
			return 0, err
		}
		tmp36 = tmp38
	} else {
		tmp39, err := this.RoutingHeader.(*CcsdsPrimaryHeader).PacketType()
		if err != nil {
			return 0, err
		}
		tmp36 = tmp39
	}
	this.globalPacketType = int(tmp36)
	return this.globalPacketType, nil
}

/**
 * true = SNLP (Community), false = CCSDS (Enterprise).
 */
func (this *VoidProtocol) IsSnlp() (v bool, err error) {
	if (this._f_isSnlp) {
		return this.isSnlp, nil
	}
	this._f_isSnlp = true
	tmp40, err := this.MagicPeek()
	if err != nil {
		return false, err
	}
	this.isSnlp = bool(tmp40 == 486647205)
	return this.isSnlp, nil
}

/**
 * Peek first 4 bytes without consuming. Used for header selection.
 */
func (this *VoidProtocol) MagicPeek() (v uint32, err error) {
	if (this._f_magicPeek) {
		return this.magicPeek, nil
	}
	this._f_magicPeek = true
	_pos, err := this._io.Pos()
	if err != nil {
		return 0, err
	}
	_, err = this._io.Seek(int64(0), io.SeekStart)
	if err != nil {
		return 0, err
	}
	tmp41, err := this._io.ReadU4be()
	if err != nil {
		return 0, err
	}
	this.magicPeek = tmp41
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return 0, err
	}
	return this.magicPeek, nil
}

/**
 * Collision resolver for 122-byte bodies.
 * Packet D (Delivery) vs Packet ACK SNLP (Command).
 * 
 * TIER CONSTRAINT: body_length=122 is reachable by CCSDS Packet D
 * (128 − 6 hdr), SNLP Packet D (136 − 14 hdr), and SNLP ACK
 * (136 − 14 hdr). CCSDS ACK body is 114 bytes and is dispatched
 * directly at the root (F-04 fix, Option B), so the ACK branch
 * here is SNLP-only by construction.
 * 
 * F-03 FIX (VOID-006, 2026-04-15): dispatch now switches on the
 * `magic` byte at body offset 0, NOT on the CCSDS Type bit. The
 * Type bit is a single point of failure (one bit-flip = wrong
 * parse path). The magic byte is an 8-bit discriminant with
 * Hamming distance 4 between 0xD0 and 0xAC — a single RF bit
 * error cannot transform one into the other. An unknown magic
 * value is a hard parse failure and MUST bounce at the gateway
 * ingest boundary before any body-specific interpretation.
 */
type VoidProtocol_Dispatch122 struct {
	Content kaitai.Struct
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
	_f_magicPeek bool
	magicPeek uint8
}
func NewVoidProtocol_Dispatch122() *VoidProtocol_Dispatch122 {
	return &VoidProtocol_Dispatch122{
	}
}

func (this VoidProtocol_Dispatch122) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_Dispatch122) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp42, err := this.MagicPeek()
	if err != nil {
		return err
	}
	switch (tmp42) {
	case 172:
		tmp43 := NewVoidProtocol_PacketAckBodySnlp()
		err = tmp43.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Content = tmp43
	case 208:
		tmp44 := NewVoidProtocol_PacketDBody()
		err = tmp44.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Content = tmp44
	}
	return err
}

/**
 * Peek body offset 0 without consuming. Selects body type.
 */
func (this *VoidProtocol_Dispatch122) MagicPeek() (v uint8, err error) {
	if (this._f_magicPeek) {
		return this.magicPeek, nil
	}
	this._f_magicPeek = true
	_pos, err := this._io.Pos()
	if err != nil {
		return 0, err
	}
	_, err = this._io.Seek(int64(0), io.SeekStart)
	if err != nil {
		return 0, err
	}
	tmp45, err := this._io.ReadU1()
	if err != nil {
		return 0, err
	}
	this.magicPeek = tmp45
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return 0, err
	}
	return this.magicPeek, nil
}

/**
 * System Heartbeat. Health, status, and GPS telemetry.
 * Transmitted periodically for ground station monitoring.
 * 34 bytes payload.
 * 
 * VOID-114B: field order matches C++ HeartbeatPacket_t in
 * void_packets_{ccsds,snlp}.h and Go generator genPacketL.
 * _pad_head added so epoch_ts lands on 8-byte boundary.
 * The legacy reserved[2] field is dropped (never used);
 * _pad_head is the forward-compat slot.
 */
type VoidProtocol_HeartbeatBody struct {
	PadHead []byte
	EpochTs uint64
	PressurePa uint32
	LatFixed int32
	LonFixed int32
	VbattMv uint16
	TempC int16
	GpsSpeedCms uint16
	SysState TigCommonTypes_SysState
	SatLock uint8
	Crc32 uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_HeartbeatBody() *VoidProtocol_HeartbeatBody {
	return &VoidProtocol_HeartbeatBody{
	}
}

func (this VoidProtocol_HeartbeatBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_HeartbeatBody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp46, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp46 = tmp46
	this.PadHead = tmp46
	tmp47, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.EpochTs = uint64(tmp47)
	tmp48, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PressurePa = uint32(tmp48)
	tmp49, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.LatFixed = int32(tmp49)
	tmp50, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.LonFixed = int32(tmp50)
	tmp51, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.VbattMv = uint16(tmp51)
	tmp52, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.TempC = int16(tmp52)
	tmp53, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.GpsSpeedCms = uint16(tmp53)
	tmp54, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SysState = TigCommonTypes_SysState(tmp54)
	tmp55, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SatLock = tmp55
	tmp56, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp56)
	return err
}

/**
 * Cycle alignment pad (VOID-114B). Pushes epoch_ts to 8-aligned.
 */

/**
 * Unix timestamp.
 */

/**
 * Barometric pressure in Pascals.
 */

/**
 * Latitude * 10^7 (e.g., 515000000 = 51.5° N). Signed: negative = South.
 */

/**
 * Longitude * 10^7 (e.g., -128000 = -0.0128° W). Signed: negative = West.
 */

/**
 * Battery voltage in millivolts.
 */

/**
 * Internal temp in centidegrees (2300 = 23.00°C).
 */

/**
 * Ground speed in cm/s (600 = 6.0 m/s).
 */

/**
 * State machine ID.
 */

/**
 * GPS satellite count.
 */

/**
 * Heartbeat integrity checksum.
 */

/**
 * The Invoice. Broadcast by Sat A (Seller).
 * Unsigned public offer of service. 66 bytes payload.
 * 
 * VOID-114B: _pad_head and _pre_crc added so epoch_ts lands on
 * a natural 8-byte boundary and crc32 on a 4-byte boundary
 * under both 6B CCSDS and 14B SNLP headers.
 */
type VoidProtocol_PacketABody struct {
	PadHead []byte
	EpochTs uint64
	PosVec *TigCommonTypes_Vector3d
	VelVec *TigCommonTypes_Vector3f
	SatId uint32
	Amount uint64
	AssetId TigCommonTypes_AssetId
	PreCrc []byte
	Crc32 uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketABody() *VoidProtocol_PacketABody {
	return &VoidProtocol_PacketABody{
	}
}

func (this VoidProtocol_PacketABody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketABody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp57, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp57 = tmp57
	this.PadHead = tmp57
	tmp58, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.EpochTs = uint64(tmp58)
	tmp59 := NewTigCommonTypes_Vector3d()
	err = tmp59.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.PosVec = tmp59
	tmp60 := NewTigCommonTypes_Vector3f()
	err = tmp60.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.VelVec = tmp60
	tmp61, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SatId = uint32(tmp61)
	tmp62, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.Amount = uint64(tmp62)
	tmp63, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.AssetId = TigCommonTypes_AssetId(tmp63)
	tmp64, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp64 = tmp64
	this.PreCrc = tmp64
	tmp65, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp65)
	return err
}

/**
 * Cycle alignment pad (VOID-114B). Pushes epoch_ts to 8-aligned.
 */

/**
 * Unix timestamp. Replay protection.
 */

/**
 * Sat A ECEF position.
 */

/**
 * Sat A velocity vector.
 */

/**
 * 32-bit Seller Identifier.
 */

/**
 * Cost in lowest denomination (e.g., Satoshi).
 */

/**
 * Currency Type ID. MUST be a verified stablecoin.
 */

/**
 * CRC alignment pad (VOID-114B). Pushes crc32 to 4-aligned.
 */

/**
 * Invoice integrity checksum.
 */

/**
 * Ground Station Acknowledgement / Unlock Command — CCSDS tier.
 * 
 * Total body: 114 bytes (frame 120 = 6B CCSDS header + 114B body).
 * Contains Relay Instructions and the encrypted unlock key.
 * enc_tunnel is fixed at 88 bytes (compact, standard CCSDS header).
 * 
 * F-04 FIX (Option B): split from the former polymorphic packet_ack_body
 * so every field has a compile-time offset. Statically analyzable.
 * 
 * F-03 FIX (VOID-006, 2026-04-15): `magic` at body offset 0 is a
 * packet-type discriminant. Value 0xAC identifies ACK. Absorbed
 * from the former 2-byte pad_a (now 1 byte). Body total, frame
 * total, and all downstream field offsets unchanged.
 */
type VoidProtocol_PacketAckBodyCcsds struct {
	Magic []byte
	PadA []byte
	TargetTxId uint32
	Status TigCommonTypes_SettlementStatus
	PadB []byte
	RelayOps *TigCommonTypes_RelayOps
	EncTunnel []byte
	PadC []byte
	Crc32 uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketAckBodyCcsds() *VoidProtocol_PacketAckBodyCcsds {
	return &VoidProtocol_PacketAckBodyCcsds{
	}
}

func (this VoidProtocol_PacketAckBodyCcsds) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketAckBodyCcsds) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp66, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp66 = tmp66
	this.Magic = tmp66
	if !(bytes.Equal(this.Magic, []uint8{172})) {
		return kaitai.NewValidationNotEqualError([]uint8{172}, this.Magic, this._io, "/types/packet_ack_body_ccsds/seq/0")
	}
	tmp67, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp67 = tmp67
	this.PadA = tmp67
	tmp68, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TargetTxId = uint32(tmp68)
	tmp69, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Status = TigCommonTypes_SettlementStatus(tmp69)
	tmp70, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp70 = tmp70
	this.PadB = tmp70
	tmp71 := NewTigCommonTypes_RelayOps()
	err = tmp71.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.RelayOps = tmp71
	tmp72, err := this._io.ReadBytes(int(88))
	if err != nil {
		return err
	}
	tmp72 = tmp72
	this.EncTunnel = tmp72
	tmp73, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp73 = tmp73
	this.PadC = tmp73
	tmp74, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp74)
	return err
}

/**
 * Packet-ACK discriminant (F-03 fix). MUST be 0xAC.
 */

/**
 * 32/64-bit alignment pad (1 byte after magic absorption).
 */

/**
 * Cleartext transaction nonce being acknowledged.
 */

/**
 * 0x01=Settled, 0xFF=Rejected.
 */

/**
 * Data boundary pad.
 */

/**
 * 12-byte Sat B relay instructions.
 */

/**
 * ChaCha20 encrypted tunnel data. Fixed 88B (CCSDS tier).
 * Decrypted payload is TunnelData_t (see Acknowledgment-spec.md § C).
 */

/**
 * Alignment to CRC boundary.
 */

/**
 * Outer checksum.
 */

/**
 * Ground Station Acknowledgement / Unlock Command — SNLP tier.
 * 
 * Total body: 122 bytes (frame 136 = 14B SNLP header + 122B body).
 * Contains Relay Instructions and the encrypted unlock key.
 * enc_tunnel is fixed at 96 bytes (padded for SNLP internal header).
 * 
 * F-04 FIX (Option B): split from the former polymorphic packet_ack_body
 * so every field has a compile-time offset. Statically analyzable.
 * 
 * F-03 FIX (VOID-006, 2026-04-15): `magic` at body offset 0 is a
 * packet-type discriminant. Value 0xAC identifies ACK and protects
 * dispatch_122 against single-bit-flip collisions with Packet D
 * (which shares body_length=122 in this tier). Absorbed from the
 * former 2-byte pad_a (now 1 byte). Body total, frame total, and
 * all downstream field offsets unchanged.
 */
type VoidProtocol_PacketAckBodySnlp struct {
	Magic []byte
	PadA []byte
	TargetTxId uint32
	Status TigCommonTypes_SettlementStatus
	PadB []byte
	RelayOps *TigCommonTypes_RelayOps
	EncTunnel []byte
	PadC []byte
	Crc32 uint32
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol_Dispatch122
}
func NewVoidProtocol_PacketAckBodySnlp() *VoidProtocol_PacketAckBodySnlp {
	return &VoidProtocol_PacketAckBodySnlp{
	}
}

func (this VoidProtocol_PacketAckBodySnlp) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketAckBodySnlp) Read(io *kaitai.Stream, parent *VoidProtocol_Dispatch122, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp75, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp75 = tmp75
	this.Magic = tmp75
	if !(bytes.Equal(this.Magic, []uint8{172})) {
		return kaitai.NewValidationNotEqualError([]uint8{172}, this.Magic, this._io, "/types/packet_ack_body_snlp/seq/0")
	}
	tmp76, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp76 = tmp76
	this.PadA = tmp76
	tmp77, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TargetTxId = uint32(tmp77)
	tmp78, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Status = TigCommonTypes_SettlementStatus(tmp78)
	tmp79, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp79 = tmp79
	this.PadB = tmp79
	tmp80 := NewTigCommonTypes_RelayOps()
	err = tmp80.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.RelayOps = tmp80
	tmp81, err := this._io.ReadBytes(int(96))
	if err != nil {
		return err
	}
	tmp81 = tmp81
	this.EncTunnel = tmp81
	tmp82, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp82 = tmp82
	this.PadC = tmp82
	tmp83, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp83)
	return err
}

/**
 * Packet-ACK discriminant (F-03 fix). MUST be 0xAC.
 */

/**
 * 32/64-bit alignment pad (1 byte after magic absorption).
 */

/**
 * Cleartext transaction nonce being acknowledged.
 */

/**
 * 0x01=Settled, 0xFF=Rejected.
 */

/**
 * Data boundary pad.
 */

/**
 * 12-byte Sat B relay instructions.
 */

/**
 * ChaCha20 encrypted tunnel data. Fixed 96B (SNLP tier).
 * Decrypted payload is TunnelData_t (see Acknowledgment-spec.md § C).
 */

/**
 * Alignment to CRC boundary.
 */

/**
 * Outer checksum.
 */

/**
 * The Encrypted Payment. Sent by Sat B (Mule) to Ground Station.
 * 178 bytes payload (174 data + 4-byte _tail_pad).
 * 
 * Encryption Logic:
 *   Enterprise (CCSDS): enc_payload is ChaCha20-Poly1305 ciphertext.
 *   Community (SNLP):   enc_payload is PLAINTEXT (amateur radio compliance).
 * 
 * VOID-110: ChaCha20 nonce is derived as sat_id[4] || epoch_ts[8]
 * (12 bytes). It is NEVER transmitted on the wire. The former
 * `nonce` field is now `_pre_sig` (alignment pad).
 * 
 * VOID-114B: _pad_head, _pre_sat, _pre_sig, and _tail_pad added
 * so every critical field (epoch_ts, sat_id, signature, global_crc)
 * lands on its natural alignment boundary under both headers.
 * Signature covers header + body[0..105] (106 body bytes).
 */
type VoidProtocol_PacketBBody struct {
	PadHead []byte
	EpochTs uint64
	PosVec *TigCommonTypes_Vector3d
	EncPayload []byte
	PreSat []byte
	SatId uint32
	PreSig []byte
	Signature *TigCommonTypes_Ed25519Signature
	GlobalCrc uint32
	TailPad []byte
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketBBody() *VoidProtocol_PacketBBody {
	return &VoidProtocol_PacketBBody{
	}
}

func (this VoidProtocol_PacketBBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketBBody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp84, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp84 = tmp84
	this.PadHead = tmp84
	tmp85, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.EpochTs = uint64(tmp85)
	tmp86 := NewTigCommonTypes_Vector3d()
	err = tmp86.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.PosVec = tmp86
	tmp87, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp87 = tmp87
	this.EncPayload = tmp87
	tmp88, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp88 = tmp88
	this.PreSat = tmp88
	tmp89, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SatId = uint32(tmp89)
	tmp90, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp90 = tmp90
	this.PreSig = tmp90
	tmp91 := NewTigCommonTypes_Ed25519Signature()
	err = tmp91.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Signature = tmp91
	tmp92, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GlobalCrc = uint32(tmp92)
	tmp93, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp93 = tmp93
	this.TailPad = tmp93
	return err
}

/**
 * Cycle alignment pad (VOID-114B). Pushes epoch_ts to 8-aligned.
 */

/**
 * Sat B timestamp. Used for nonce derivation (VOID-110).
 */

/**
 * Sat B ECEF position. Cleartext.
 */

/**
 * Inner Invoice (62 bytes).
 * Plaintext if SNLP, ChaCha20 ciphertext if CCSDS.
 */

/**
 * sat_id alignment pad (VOID-114B). Pushes sat_id to 4-aligned.
 */

/**
 * Sat B ID (Mule). 32-bit global identity.
 */

/**
 * Signature alignment pad (VOID-114B). Pushes signature to 8-aligned.
 */

/**
 * Ed25519 PUF Signature over header + body[0..105].
 */

/**
 * Outer packet integrity checksum.
 */

/**
 * Frame tail pad (VOID-114B). CCSDS total 184 (÷8), SNLP total 192 (÷64 cache line).
 */

/**
 * The Receipt (Proof of Execution).
 * Generated by Sat A after successful service dispensation.
 */
type VoidProtocol_PacketCBody struct {
	PadHead []byte
	ExecTime uint64
	EncTxId uint64
	EncStatus uint8
	PadSig []byte
	Signature *TigCommonTypes_Ed25519Signature
	Crc32 uint32
	TailPad []byte
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketCBody() *VoidProtocol_PacketCBody {
	return &VoidProtocol_PacketCBody{
	}
}

func (this VoidProtocol_PacketCBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketCBody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp94, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp94 = tmp94
	this.PadHead = tmp94
	tmp95, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.ExecTime = uint64(tmp95)
	tmp96, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.EncTxId = uint64(tmp96)
	tmp97, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.EncStatus = tmp97
	tmp98, err := this._io.ReadBytes(int(7))
	if err != nil {
		return err
	}
	tmp98 = tmp98
	this.PadSig = tmp98
	tmp99 := NewTigCommonTypes_Ed25519Signature()
	err = tmp99.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Signature = tmp99
	tmp100, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp100)
	tmp101, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp101 = tmp101
	this.TailPad = tmp101
	return err
}

/**
 * Cycle alignment pad.
 */

/**
 * Execution timestamp.
 */

/**
 * Encrypted Transaction ID. Matches Tunnel BLOCK_NONCE.
 */

/**
 * Encrypted status byte. 0x01=Success after decryption.
 */

/**
 * Signature alignment pad (pushes signature to 8-byte boundary).
 */

/**
 * Sat A PUF signature over offsets 00-31.
 */

/**
 * Receipt integrity checksum.
 */

/**
 * Final alignment to 98 bytes.
 */

/**
 * The Delivery. Transport wrapper used by Sat B to downlink
 * Packet C to the Ground Station. Wraps the receipt in a new
 * CCSDS/SNLP frame for radio transmission.
 * 
 * F-03 FIX (VOID-006, 2026-04-15): `magic` at body offset 0 is
 * a packet-type discriminant that protects dispatch_122 against
 * single-bit-flip collisions with Packet ACK SNLP. Value 0xD0
 * identifies this as Delivery. The byte is absorbed from the
 * former 2-byte pad_head (now 1 byte), so body total, frame
 * total, and every subsequent field offset remain unchanged
 * (downlink_ts still lands on the natural 64-bit boundary).
 */
type VoidProtocol_PacketDBody struct {
	Magic []byte
	PadHead []byte
	DownlinkTs uint64
	SatBId uint32
	Payload []byte
	GlobalCrc uint32
	Tail []byte
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol_Dispatch122
}
func NewVoidProtocol_PacketDBody() *VoidProtocol_PacketDBody {
	return &VoidProtocol_PacketDBody{
	}
}

func (this VoidProtocol_PacketDBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketDBody) Read(io *kaitai.Stream, parent *VoidProtocol_Dispatch122, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp102, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp102 = tmp102
	this.Magic = tmp102
	if !(bytes.Equal(this.Magic, []uint8{208})) {
		return kaitai.NewValidationNotEqualError([]uint8{208}, this.Magic, this._io, "/types/packet_d_body/seq/0")
	}
	tmp103, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp103 = tmp103
	this.PadHead = tmp103
	tmp104, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.DownlinkTs = uint64(tmp104)
	tmp105, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SatBId = uint32(tmp105)
	tmp106, err := this._io.ReadBytes(int(98))
	if err != nil {
		return err
	}
	tmp106 = tmp106
	this.Payload = tmp106
	tmp107, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GlobalCrc = uint32(tmp107)
	tmp108, err := this._io.ReadBytes(int(6))
	if err != nil {
		return err
	}
	tmp108 = tmp108
	this.Tail = tmp108
	return err
}

/**
 * Packet-D discriminant (F-03 fix). MUST be 0xD0.
 */

/**
 * Cycle alignment pad (1 byte after magic absorption).
 */

/**
 * Downlink timestamp.
 */

/**
 * Carrier ID (Sat B / Mule).
 */

/**
 * Stripped Packet C (CCSDS header removed).
 */

/**
 * Outer integrity checksum.
 */

/**
 * Final alignment to 122 bytes.
 */

/**
 * Ephemeral Key Exchange. Bidirectional.
 * MUST complete before any Packet B or ACK is transmitted.
 */
type VoidProtocol_PacketHBody struct {
	SessionTtl uint16
	Timestamp uint64
	EphPubKey *TigCommonTypes_X25519PublicKey
	Signature *TigCommonTypes_Ed25519Signature
	_io *kaitai.Stream
	_root *VoidProtocol
	_parent *VoidProtocol
}
func NewVoidProtocol_PacketHBody() *VoidProtocol_PacketHBody {
	return &VoidProtocol_PacketHBody{
	}
}

func (this VoidProtocol_PacketHBody) IO_() *kaitai.Stream {
	return this._io
}

func (this *VoidProtocol_PacketHBody) Read(io *kaitai.Stream, parent *VoidProtocol, root *VoidProtocol) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp109, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.SessionTtl = uint16(tmp109)
	tmp110, err := this._io.ReadU8le()
	if err != nil {
		return err
	}
	this.Timestamp = uint64(tmp110)
	tmp111 := NewTigCommonTypes_X25519PublicKey()
	err = tmp111.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.EphPubKey = tmp111
	tmp112 := NewTigCommonTypes_Ed25519Signature()
	err = tmp112.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Signature = tmp112
	return err
}

/**
 * Session duration in seconds.
 */

/**
 * Session start time (Unix epoch).
 */

/**
 * X25519 ephemeral public key (32 bytes).
 */

/**
 * Ed25519 identity signature over offsets 00-47.
 */
